steps:
  # 1. Main-Branch -> :latest
  publish-latest:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: rondevhub/mastodon-share
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      tags: latest
      dockerfile: Dockerfile
      context: .
    when:
      branch: main
      event: push

  # 2. Beta-Branch -> :beta
  publish-beta:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: rondevhub/mastodon-share
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      tags: beta
      dockerfile: Dockerfile
      context: .
    when:
      branch: beta
      event: manual

  # 3. Release-Tags -> :v1.0.0
  publish-tag:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: rondevhub/mastodon-share
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
      tags: ${CI_COMMIT_TAG}
      dockerfile: Dockerfile
      context: .
    when:
      event: tag